config/routes.rb
Rails.application.routes.draw do
 

  resources :infoleys
  
 get  '/contacto',    to: 'contactos#index'
 get 'contacto/new'
 resources :contactos
 resources :microposts

  root 'informacion_leyes#index'
  
 get 'contactos/index'
  get "informacion_leyes/brazil"

end

app/models/infoley.rb
class Infoley < ActiveRecord::Base
end

app/models/informacion_ley.rb
class InformacionLey < ActiveRecord::Base
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
    default_scope -> { order(created_at: :desc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contactos_controller.rb
class ContactosController < ApplicationController
  def index
     @microposts = Micropost.all
     @micropost = Micropost.new
  end
end

app/controllers/infoleys_controller.rb
class InfoleysController < ApplicationController
  before_action :set_infoley, only: [:show, :edit, :update, :destroy]

  # GET /infoleys
  # GET /infoleys.json
  def index
    @infoleys = Infoley.all
  end

  # GET /infoleys/1
  # GET /infoleys/1.json
  def show
  end

  # GET /infoleys/new
  def new
    @infoley = Infoley.new
  end

  # GET /infoleys/1/edit
  def edit
  end

  # POST /infoleys
  # POST /infoleys.json
  def create
    @infoley = Infoley.new(infoley_params)

    respond_to do |format|
      if @infoley.save
        format.html { redirect_to @infoley, notice: 'Infoley was successfully created.' }
        format.json { render :show, status: :created, location: @infoley }
      else
        format.html { render :new }
        format.json { render json: @infoley.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /infoleys/1
  # PATCH/PUT /infoleys/1.json
  def update
    respond_to do |format|
      if @infoley.update(infoley_params)
        format.html { redirect_to @infoley, notice: 'Infoley was successfully updated.' }
        format.json { render :show, status: :ok, location: @infoley }
      else
        format.html { render :edit }
        format.json { render json: @infoley.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /infoleys/1
  # DELETE /infoleys/1.json
  def destroy
    @infoley.destroy
    respond_to do |format|
      format.html { redirect_to infoleys_url, notice: 'Infoley was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_infoley
      @infoley = Infoley.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def infoley_params
      params.require(:infoley).permit(:numero_ley, :fecha, :tipo, :exp_simpl, :cont_ley, :proy_ley)
    end
end

app/controllers/informacion_leyes_controller.rb
class InformacionLeyesController < ApplicationController
require "http"
require 'nokogiri'
require 'open-uri'
require 'rexml/document'
require 'net/http'
include REXML
#ley facil
#boton de peticion de ley facil, conforme a la demanda.
#http://www.leychile.cl/Consulta/obtxml?opt=7&idNorma=&idLey=20066

def index
    
    
 @ley= "Esperando busqueda"
    @paisLey="Chile"
     #Persona.where("persona_rut= ?", @prestamo.persona_id)
 #!Infoley.where("numero_ley= ?",  params[:numley])  
 
 
 
 
@ley_buscada = Infoley.find_by(numero_ley:  params[:numley])
if  !@ley_buscada.present?

    #@infoleys = Infoley.all
    @numley= params[:numley].to_s
     
  if @numley.blank?
      @numley="20830"
  end
  
    xml = Net::HTTP.get(URI.parse('http://www.leychile.cl/Consulta/obtxml?opt=7&idNorma=&idLey=' + @numley )) #20066 18290ley existe
    data = Hash.from_xml(xml)
   
   
   

  
  
  xmldoc = Document.new(xml)
  XPath.each(xmldoc, "//Texto") { |e| 
  #puts e.text
  #@ley= "#{e.text}"
  @ley = "#{@ley} : #{e.text}"
  }

    @fecha=data["Norma"]["Identificador"]["fechaPromulgacion"]
    @numero=data["Norma"]["Identificador"]["TiposNumeros"]["TipoNumero"]["Numero"]
    @tipo=data["Norma"]["Identificador"]["TiposNumeros"]["TipoNumero"]["Tipo"]
    @info = data["Norma"]["Identificador"]["fechaPromulgacion"]
    @expl_simp= "Explicacion simplificada leyfacil"
    @proy_ley="proyecto de ley"
    
    Infoley.create(numero_ley:@numero, fecha:@fecha, tipo:@tipo, exp_simpl:@expl_simp, cont_ley:@ley, proy_ley:@proy_ley, pais:@paisLey)

else
    
    if @ley_buscada.pais == "Brazil"
        print "entramos·····#######################################"
       numley = "20660"
        @ley_buscada = Infoley.find_by(numero_ley:  "20660")
       
    end
     @fecha= @ley_buscada.fecha
     @numero= @ley_buscada.numero_ley
     @tipo= @ley_buscada.tipo
     @expl_simp= @ley_buscada.exp_simpl
     @ley= @ley_buscada.cont_ley
  
end  
end





def brazil
    @paisLey="Brazil" 
    
     
@ley_buscada = Infoley.find_by(numero_ley:  params[:numley2])
#if  !@ley_buscada.present?

    #@infoleys = Infoley.all
    @numley= params[:numley2].to_s
     
  if @numley.blank?
      @numley="11652"
  end
  @ano = "2008"
  
    xml = Net::HTTP.get(URI.parse('http://legis.senado.leg.br/dadosabertos/legislacao/lei/' + @numley + "/" + @ano)) #20066 18290ley existe
    data = Hash.from_xml(xml)
   
   
   

  
  
  xmldoc = Document.new(xml)

#tomamos la pagina en bruto
#file = Net::HTTP.get(URI.parse("http://legis.senado.leg.br/legislacao/ListaTextoIntegral.action?id=236051&ampnorma=256999")).to_s
file = Nokogiri::HTML(open 'http://legis.senado.leg.br/legislacao/ListaTextoIntegral.action?id=236051&ampnorma=256999')
@contents = file.to_s






  XPath.each(xmldoc, "//LinkTexto") { 
    |e| 
  #puts e.text
  #@ley= "#{e.text}"
 @ley2 = "#{@ley2} #{e.text}"
 }

    @fecha=data["DetalheNorma"]["Normas"]["Norma"]["DataAssinatura"]
    @numero=data["DetalheNorma"]["Normas"]["Norma"]["Numero"]
    #@tipo=data["Norma"]["Identificador"]["TiposNumeros"]["TipoNumero"]["Tipo"]
    #@info = data["Norma"]["Identificador"]["fechaPromulgacion"]
    @expl_simp= "Explicacion simplificada leyfacil"
    @proy_ley="proyecto de ley"
    
    Infoley.create(numero_ley:@numero, fecha:@fecha, tipo:@tipo, exp_simpl:@expl_simp, cont_ley:@ley, proy_ley:@proy_ley, pais:@paisLey)

#else
    
 #    @fecha= @ley_buscada.fecha
  #   @numero= @ley_buscada.numero_ley
   #  @tipo= @ley_buscada.tipo
    # @expl_simp= @ley_buscada.exp_simpl
     #@ley= @ley_buscada.cont_ley
  
#end  



end



 






end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
     def create
    @micropost = Micropost.new(micropost_params)    
    if @micropost.save
      #log_in @adm
      
       redirect_to contacto_path
    else
      render 'new'
    end
  end
  
  private

    def micropost_params
      params.require(:micropost).permit(:nombre, :content, :num)
    end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contactos_helper.rb
module ContactosHelper
end

app/helpers/infoleys_helper.rb
module InfoleysHelper
end

app/helpers/informacion_leyes_helper.rb
module InformacionLeyesHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/contactos/index.html.erb
<div class="container">
    <div class="panel panel-default" > 
    
    
   
    
    
     <div class="row">
            
            
            
            <div class="col-md-5">
               
            </div>
            <div class="col-md-4">
                
               
              
               
            </div>
           
            
            
    </div>
    
    
    
    
    
    
           
    
        
        <div class="row">
            
            
            <div>
            <div class="col-md-6">
                <div class="panel panel-success">
                
                    <div class="panel-heading">Déjanos tu comentario</div>
                    <div class="panel-body  panel-height">
                        

                    <%= form_for(@micropost) do |f| %>
                    
                    
                      <%= f.label :Nombre %>
                      <%= f.text_field :nombre, placeholder: "Escribir Nombre" %> 
                       <%= f.label :Numero_Ley %>
                      <%= f.text_field :num, placeholder: "Escribir Número Ley" %> 
                      <div class="field">
                      <%= f.label :Comentario %><br>
                       <%= f.text_area :content, placeholder: "Escribir comentario", size: "60x10" %>
                      </div>
                     
                      <%= f.submit "Aceptar", class: "btn button" %>
                    <% end %>

                        
                        
                    </div>
                
                </div>
            </div>
            
            <div class="col-md-6">
                
                <div class="panel panel-warning">
                    <div class="panel-heading">Comentarios</div>
                    <div class="panel-body panel-height ">
                        <div class="col-md-8">
                            
                              
                              <ol class="microposts">
                                <%= render @microposts %>
                              </ol>
                             
                          </div>

                        
                        
                    </div>
                </div>
                
            </div>
            </div>
            
        </div>
    </div>
</div>


                    
                  

app/views/infoleys/_form.html.erb
<%= form_for(@infoley) do |f| %>
  <% if @infoley.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@infoley.errors.count, "error") %> prohibited this infoley from being saved:</h2>

      <ul>
      <% @infoley.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :numero_ley %><br>
    <%= f.text_field :numero_ley %>
  </div>
  <div class="field">
    <%= f.label :fecha %><br>
    <%= f.datetime_select :fecha %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.text_field :tipo %>
  </div>
  <div class="field">
    <%= f.label :exp_simpl %><br>
    <%= f.text_area :exp_simpl %>
  </div>
  <div class="field">
    <%= f.label :cont_ley %><br>
    <%= f.text_area :cont_ley %>
  </div>
  <div class="field">
    <%= f.label :proy_ley %><br>
    <%= f.text_area :proy_ley %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/infoleys/edit.html.erb
<h1>Editing Infoley</h1>

<%= render 'form' %>

<%= link_to 'Show', @infoley %> |
<%= link_to 'Back', infoleys_path %>

app/views/infoleys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Infoleys</h1>

<table>
  <thead>
    <tr>
      <th>Numero ley</th>
      <th>Fecha</th>
      <th>Tipo</th>
      <th>Exp simpl</th>
      <th>Cont ley</th>
      <th>Proy ley</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @infoleys.each do |infoley| %>
      <tr>
        <td><%= infoley.numero_ley %></td>
        <td><%= infoley.fecha %></td>
        <td><%= infoley.tipo %></td>
        <td><%= infoley.exp_simpl %></td>
        <td><%= infoley.cont_ley %></td>
        <td><%= infoley.proy_ley %></td>
        <td><%= link_to 'Show', infoley %></td>
        <td><%= link_to 'Edit', edit_infoley_path(infoley) %></td>
        <td><%= link_to 'Destroy', infoley, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Infoley', new_infoley_path %>

app/views/infoleys/new.html.erb
<h1>New Infoley</h1>

<%= render 'form' %>

<%= link_to 'Back', infoleys_path %>

app/views/infoleys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numero ley:</strong>
  <%= @infoley.numero_ley %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @infoley.fecha %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @infoley.tipo %>
</p>

<p>
  <strong>Exp simpl:</strong>
  <%= @infoley.exp_simpl %>
</p>

<p>
  <strong>Cont ley:</strong>
  <%= @infoley.cont_ley %>
</p>

<p>
  <strong>Proy ley:</strong>
  <%= @infoley.proy_ley %>
</p>

<%= link_to 'Edit', edit_infoley_path(@infoley) %> |
<%= link_to 'Back', infoleys_path %>

app/views/informacion_leyes/brazil.html.erb
 


<div class="container">
    <div class="panel panel-default" > 
    
    
    <%= link_to "Contato", contacto_path %>
    
    
     <div class="row">
            
            
            
            <div class="col-md-5">
               
            </div>
            <div class="col-md-4">
                
               
                <strong> <h3> Número de lei Consultadas: <%=@numero %> </h3></strong>
               
            </div>
            <div class="col-md-1">
                </div>
            <div class="col-md-2">
                <%= link_to " Comentário Lei", contacto_path, class: "btn btn-default glyphicon glyphicon-pencil" %>
                </div>
            
            
    </div>
    
    
    
    
    
    
    <div class="row">
            
            
            <div class="col-md-3">
            </div>
            <div class="col-md-7">
              
               
                <%#= image_tag "politicos/972.jpg", :alt => "177", :title => "177", :size => "70x70"%>
                <%#= image_tag "politicos/850.jpg", :alt => "177", :title => "177", :size => "70x70"%>
                <%#= image_tag "politicos/860.jpg", :alt => "177", :title => "177", :size => "70x70"%>
                <%#= image_tag "politicos/867.jpg", :alt => "177", :title => "177", :size => "70x70"%>
                <%#= image_tag "politicos/883.jpg", :alt => "177", :title => "177", :size => "70x70"%>
                <%#= image_tag "politicos/902.jpg", :alt => "177", :title => "177", :size => "70x70"%>
                <%#= image_tag "politicos/937.jpg", :alt => "177", :title => "177", :size => "70x70"%>
                <%#s= image_tag "politicos/991.jpg", :alt => "177", :title => "177", :size => "70x70"%>
                
            
            </div>
        
            
            
    </div>
           
    
        
        <div class="row">
            
            
            <div>
            <div class="col-md-6">
                <div class="panel panel-success">
                
                    <div class="panel-heading">Explicação Simplificada</div>
                    <div class="panel-body  panel-height"><%=@expl_simp%></div>
                
                </div>
            </div>
            
            <div class="col-md-6">
                
                
                

                
                <div class="panel panel-warning">
                    <div class="panel-heading">Lei</div>
                    <div class="panel-body panel-height ">
                        
                        <%= link_to "Ir Lei: " + @numero, @ley2 %><br>
                        
                        <%== @contents%>
                   <!-- <iframe src="http://www.w3schools.com" width="100%" height="100%">aaa</iframe>-->
                    </div>
                </div>
                
            </div>
            </div>
            
        </div>
    </div>
</div>




                  

app/views/informacion_leyes/index.html.erb
<div class="container">
    <div class="panel panel-default" > 
    <br>
    
    
    
    
     <div class="row">
            
            
            
            <div class="col-md-5">
               
            </div>
            <div class="col-md-4">
                
               
                <strong> <h3 >Nro. Ley Consultada: <%=@numero%></h3></strong>
               
            </div>
            
            <div class="col-md-1">
                </div>
            <div class="col-md-2">
                <%= link_to " Comentar Ley", contacto_path, class: "btn btn-default glyphicon glyphicon-pencil" %>
                </div>
           
            
            
    </div>
    
    
    
    
    
    
    <div class="row">
            
            
            <div class="col-md-3">
            </div>
            <div class="col-md-7">
              
               
                <%= image_tag "politicos/972.jpg", :alt => "177", :title => "177", :size => "70x70"%>
                <%= image_tag "politicos/850.jpg", :alt => "177", :title => "177", :size => "70x70"%>
                <%= image_tag "politicos/860.jpg", :alt => "177", :title => "177", :size => "70x70"%>
                <%= image_tag "politicos/867.jpg", :alt => "177", :title => "177", :size => "70x70"%>
                <%= image_tag "politicos/883.jpg", :alt => "177", :title => "177", :size => "70x70"%>
                <%= image_tag "politicos/902.jpg", :alt => "177", :title => "177", :size => "70x70"%>
                <%= image_tag "politicos/937.jpg", :alt => "177", :title => "177", :size => "70x70"%>
                <%= image_tag "politicos/991.jpg", :alt => "177", :title => "177", :size => "70x70"%>
                
               
            </div>
        
            
            
    </div>
           
    
        
        <div class="row">
            
            
            <div>
            <div class="col-md-6">
                
                
                
                <div class="panel panel-warning">
                    <div class="panel-heading">Ley</div>
                    <div class="panel-body panel-height "><%= @ley%></div>
                </div>
            </div>
            
            <div class="col-md-6">
                <div class="panel panel-success">
                
                    <div class="panel-heading">Explicacion Simplificada</div>
                    <div class="panel-body  panel-height"><%=@expl_simp%></div>
                
                </div>
                
            </div>
            </div>
            
        </div>
    </div>
</div>


                    
                  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <%= viewport_meta_tag %>
    <title><%= content_for?(:title) ? yield(:title) : "InfoLey" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", media: "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', rel: 'shortcut icon' %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          </div>
          
          
          <div class="col-md-3"><br>
            <a class="navbar-brand " id="blanco" href="#"><h1>eParliament</h1></a>   
           </div>
          
          
        

 
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <div class="row">
            <div class="col-md-6">
              
              
              <% if @paisLey == "Chile"%>
                <%= form_tag({ controller: 'informacion_leyes', action: 'index' }, method: 'get') do %>
                <br>
                <div class="input-group">
                <%= text_field_tag "numley",nil, :placeholder => "Ingrese numero de Ley", class: 'text_field form-control' %>
                <span class="input-group-btn">  <%= button_tag "", type: 'submit', class: "btn btn-default glyphicon glyphicon-search " %></span>
              
                </div>
                <%end%>
                <%else%>
                  <%= form_tag({ controller: 'informacion_leyes', action: 'index' }, method: 'get') do %>
                <br>
                <div class="input-group">
                <%= text_field_tag "numley2",nil, :placeholder => "Digite o número do lei", class: 'text_field form-control' %>
                <span class="input-group-btn">  <%= button_tag "", type: 'submit', class: "btn btn-default glyphicon glyphicon-search " %></span>
              
                </div>
                <%end%>
                
              <%end%>
                
                
                
            </div>
            
            <div class="col-md-1">
              
              </div>
              <div class="col-md-1">
                 <div class="pull-rigth">
                  
                  
                  
                  
                  <%= link_to root_path do %>
                      <%= image_tag "banderas/chile.png", class: "some css class here", :size => "30x30" %>
                  <% end %>
                  <%= link_to informacion_leyes_brazil_path do %>
                      <%= image_tag "banderas/brazil.png", class: "some css class here", :size => "30x30" %>
                  <% end %>

                   


                   <%#= image_tag "banderas/brazil.png", :alt => "177", :title => "177", :size => "30x30"%>
                    <%#= image_tag "banderas/chile.png", :alt => "177", :title => "177", :size => "30x30"%>
                    </div>
              </div>
            
          </div>
          
          
          
          
          
         
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>

    <div class="container">
      <div class="row">
        <div class="col-md-9" id="body">
          <%= bootstrap_flash %>
          
          
          
          <%= yield %>
          
          
        </div>
       

      <footer>
        <p>&copy; Hackaton 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  Número de la ley:  <%= micropost.num %>
  
  
  
  <br><span class="content"><%= micropost.nombre %></span>
  
  
  
  <span class="content"><%= micropost.content %></span>
  <br><span class="timestamp">
    Posteado: <%= time_ago_in_words(micropost.created_at) %> ago.
  </span></br>
</li>